### ISSUE TITLE
Bug: Oxygen depletes in bed!

### ISSUE THREAD

**Issue by BavarianViking87** [squ1b3r/vs-oxygen-not-included#1]
like the title says: Oxygen depletes in bed

**Comment by squ1b3r** [comment]
> like the title says: Oxygen depletes in bed

Ouch. That is something I would never expect. I'll take a look at it today. Thanks for the report.

**Comment by squ1b3r** [comment]
@BavarianViking87 I can't seem to reproduce it. Tried all three beds and it doesn't do what you report here. Could it be that your bed is placed in a way that pushes the player's head into a solid block?

**Comment by BavarianViking87** [comment]
> @BavarianViking87 I can't seem to reproduce it. Tried all three beds and it doesn't do what you report here. Could it be that your bed is placed in a way that pushes the player's head into a solid block?

@squ1b3r 
OK, seems it was the Fence at the trading cart. The bug doesn't happen in my own detached bed. 
Sorry

**Comment by squ1b3r** [comment]
@BavarianViking87 Hmm, did you try to use one of those beds that traders have and it suffocated you?

**Comment by squ1b3r** [comment]
@BavarianViking87 Somebody else reported a similar issue so I've changed things a bit and things like this should not be happening anything. Closing.
