### ISSUE TITLE
suffocation issues

### ISSUE THREAD

**Issue by Fathom-2** [squ1b3r/vs-oxygen-not-included#2]
Hello, I have found a few suffocation issues as follows:

Standing in a block with a door open or closed.
Standing in a block with a trap door open.
Stepping up on a stair or a slab with your head in a block occupied by a fence, an upside down stair or a slab, etc.

Thanks for your attention, great mod addition!

**Comment by squ1b3r** [comment]
@DAmnshaYmZ Thank you so much for the report!

Would you mind trying [this](https://github.com/squ1b3r/vs-oxygen-not-included/releases/tag/v0.2.2) build and see if it fixes all of those things before I release it?

**Comment by Fathom-2** [comment]
All good now, everything is working as expected.  Thank you.

**Comment by squ1b3r** [comment]
@DAmnshaYmZ Thank you for testing. Closing this.
